### PR TITLE
Adding support for `select2` events

### PR DESCRIPTION
**Pull request by joseym**
I needed to be able to fire actions when a tag was added and removed, if this functionality already existed I couldn't find it from the source.

To add events you simply need to add an `events` option to your select2 options object:

``` javascript
$scope.options = {
    multiple: true
  , tags: ['one', 'two', 'three']
  , events: {
        'open' : function(e){
          console.log(e)
        }
     ,  'removing': function(e){
          console.log('removing a tag')
        }
    }
}
```

### CODE REVIEW

**Comment by btmdave** [comment]
Perfect! This is just what I needed too!

**Comment by joseym** [comment]
apparently lint doesn't like lines starting with `,`

**Comment by ProLoser** [comment]
I don't get it. What's wrong with `ng-change` or `$watch` or `ui-event`?

**Comment by joseym** [comment]
Nothing, but what's wrong with directly supporting them as well?

**Comment by ProLoser** [comment]
You are adding functionality to the library that is in no way specific to the library. Why not then explicitly add the code to every similar directive. Secondly, why stop at just events. Why not add support for people to change css. 

These things affect the scope of an already unruly project.

**Comment by thebalaa** [comment]
@ProLoser Could you illustrate how the rest of the "select2-" events could be supported? Thanks

**Comment by ProLoser** [comment]
@thebalaa use `ui-event` from https://github.com/angular-ui/ui-utils which is SPECIFICALLY designed for this sort of thing.

It's also ridiculously easy to roll your own version of `ui-event` since all you're doing is running `$element.bind(eventName, callback)`

**Pull request closed without merging**
