### PR TITLE
feat: add $watch for changes to '.data'

### PR DESCRIPTION
**Pull request by Iristyle**
- When there is a ui-select2 attribute, the relevant model is not
  watched for changes, so refreshing possible selections is impossible
  - Add a $watch over the scope objects '.data' object, and reinit
    select2 with new options

### CODE REVIEW

**Comment by Iristyle** [comment]
FYI -- this was a quick spike that appears to be working fine... I realize that there should be accompanying tests, etc.

For now, check out this plunkr 
http://plnkr.co/edit/olQHIl6otLJf9lVCQNlB

**Comment by Iristyle** [comment]
We're also having issues with the `ng-repeat` style at the bottom -- it's not correctly populating initial values, which is why we're using code to add values to the `<input>` sytle.

If that worked, this PR wouldn't have happened :smile_cat:

**Comment by ProLoser** [comment]
So my demos on how to use ui-select2 show that if you preserve the reference (instead of doing `data = x`) then you don't actually have to reinitialize anything since select2 is smart enough to always recheck the data every time you reopen it. http://plnkr.co/edit/gist:4279651?p=preview

**Comment by Iristyle** [comment]
Ah ah - somehow missed that when I scanned your samples! :astonished:   Didn't realize `select2` had this baked in.

Will see what I can do to try and fix the issue with `ng-repeat` restoring selected objects.

**Pull request closed without merging**
