### PR TITLE
Do not set $dirty flag on init

### PR DESCRIPTION
**Pull request by dmitry-dedukhin**
With original code $dirty flag is set on select element right after page loaded, see [example](http://embed.plnkr.co/8sviCh/preview)
With fixed code $dirty flag is set only when select is really changed, see [example](http://embed.plnkr.co/HTBvdD/preview)

### CODE REVIEW

**Comment by uptownhr** [comment]
This bug is still open. $dirty flag is true on init still

**Comment by dmitry-dedukhin** [comment]
Hi,
Are there any news on this issue?

**Comment by ProLoser** [comment]
@dmitry-dedukhin does this work with multi-select since the value would be an array?

**Comment by uptownhr** [comment]
I know this is somewhat trivial now that 1.2 is stable but $setPristine is not available for people that have been using 1.0.8 and has not updated or cannot update. Anyway we can have a version that is backwards compatible? Any ideas?

**Comment by ProLoser** [comment]
@uptownhr sorry about that. I tweaked the code, let me know if that helps

**Pull request merged**
