### PR TITLE
Fix when using multiple selects inside ng-repeats

### PR DESCRIPTION
**Pull request by teamon**

### CODE REVIEW

**Comment by ProLoser** [comment]
What? Can you esplain?

**Comment by ProLoser** [comment]
This needs some tests or a demo. If what you're doing here fixes a problem, then there is more than likely a bigger issue altogether.

**Comment by teamon** [comment]
Sure,

``` js
$scope.items = [
  {id: 1, text: "A"},
  {id: 2, text: "B"}
]
```

``` html
<div ng-repeat="item in items">
   <input ui-select2 ng-model="item"/>
</div>
```

If you change selection in UI `$scope.items` is not updated, it still holds reference to old object which was replaced by `$setViewValue`. `angular.extends` do not replace object but only its contents and that solves the issue.

**Comment by ProLoser** [comment]
What if you did `ng-model="items[$index]"`?

Also, this seems like a shortcoming of $setViewValue(), no?

**Comment by teamon** [comment]
TBH I didn't know about `items[$index]`, I'll have to check that. But even if it works, imho this will still be a bug, I don't want to use `$index` in my code, `item` is much more readable and natural. 

Yep, unfortunately.

**Comment by teamon** [comment]
Confirmed - it works with `items[$index]`

**Comment by ProLoser** [comment]
I understand your reservations, the problem is that I think you run a bigger risk in the long run by avoiding `ngModel.$setViewValue()` which I believe does a lot more than simply setting the value (don't ask me what, I'm too lazy to check atm).

I think it would be more appropriate to open an issue on @angular/angular.js instead and ask them about why `$setViewValue()` breaks the reference, or if it should at all?

However, I think the response will be:

> You should be messing with properties and ALWAYS have a `.` in your models to avoid reference breaking
> If you do this instead you will have no issues:
> 
> ``` html
> <script>
> $scope.items = [
>   { name: 'Item 1', value: {id: 1, text: "A"} },
>   { name: 'Item 2', value: {id: 2, text: "B"} }
> ];
> </script>
> <div ng-repeat="item in items">
>   <input ui-select2 ng-model="item.value"/>
> </div>
> ```

**Pull request closed without merging**
