### PR TITLE
Added destroy handler to remove the select2 when the parent element is removed from DOM

### PR DESCRIPTION
**Pull request by sudhirrs**
If I have `<select ui-if='some-condition' ui-select2 ... ></select>`, when `some-condition` is false, the select2 generated artifact is left behind. I am not sure if there is a better way than doing this in a $destroy handler or I am doing my code the wrong way. - Thx

### CODE REVIEW

**Comment by ProLoser** [comment]
Shouldn't this be $scope.$on('$destroy')?

**Comment by colinmorelli** [comment]
This should be changed to $scope.$on('$destroy'). When used inside of certain directives (such as a sortable), the element throws a $destroy event but the scope does not get destroyed. Angular never re-initializes the directives, so all select2s in the sortable break. Changing it to bind to the scope makes it work as expected.

**Comment by ProLoser** [comment]
@colinmorelli you may be right, but at the same time, why is there an inconsistency between `$scope.$on('$destroy')` and `$element.bind('$destroy')`? This sounds like a bug with angular or those other scenarios where this is creeping up.

**Comment by colinmorelli** [comment]
I haven't investigated this potential cause yet, but it may be because the directive doesn't create an isolate scope. When using ui-sortable, elements aren't removed from the array, they're just re-ordered. Angular's ngRepeat has a good bit of optimization for these scenarios in which it can detect that without needing to recreate all of the elements (I believe). As a result the scope of the repeated item is never destroyed, but the contents of it are destroyed (and thus the select2 is destroyed as well).

**Comment by colinmorelli** [comment]
Found the relevant line in ngRepeat:

https://github.com/angular/angular.js/blob/ca116c35a63e06e62337ce9713a55d28ad9ebce8/src/ng/directive/ngRepeat.js#L347

When the item in the collection is an existing item that is moved, it calls $animate.move(), which ultimately calls $animate.enter():

https://github.com/angular/angular.js/blob/ca116c35a63e06e62337ce9713a55d28ad9ebce8/src/ng/animate.js#L101

This delegates to jqLite's append function which ultimately calls insertBefore. It would seem that the behavior of insertBefore is to clone the element, add it to the new position, and remove the old element (under the hood). In any case, angular doesn't destroy the actual element at all, thus the scope is never destroyed, but the contents of the (old) element in its previous position are removed causing the $destroy event to get fired.

It still may be a bug in angular, in that angular shouldn't throw the $destroy event in the case of a move, but maybe that's outside of their control.

It feels like the discrepancy between the element and scope might be considered a bug in ui-select2 as well, though? I could see the scope $destroy not being right for some users as well (if they remove the select element from the dom manually, it would actually not call select2's destroy method). Select2 could create an isolate scope and bind to that scope's $destroy event? I'll post on the angular discussion board to see if the element destroy event is intended behavior as well.

EDIT:
Post on AngularJS Group:
https://groups.google.com/forum/?hl=en#!topic/angular/61A0_FCEyIU

**Comment by jdrake** [comment]
@colinmorelli What would be the best way to reinitialize the select2s after sortable stops? I'm running into the same issue.

**Comment by ProLoser** [comment]
Subscribing to the $scope's destroy method should suffice. If you use `ng-if`, then the scope will in fact be destroyed I believe. If another directive removes the DOM it SHOULD be removing the associated $scope too.

**Comment by jdrake** [comment]
What should I call after the scope $destroy fires? I tried making a "recompile" directive and ran `$compile(element)(scope)` on scope $destroy but that was crazy slow.

**Comment by jdrake** [comment]
I ended up copying the setup code from the [initial setup](https://github.com/angular-ui/ui-select2/blob/master/src/select2.js#L199):

``` coffee
app.directive 'uiSelect2Recompile', [
  '$compile'
  '$timeout'
  ($compile, $timeout) ->
    restrict: 'A'
    require: 'ngModel'
    compile: (tElem) ->
      isSelect = tElem.is 'select'
      (scope, element, attrs, controller) ->
        options = scope.elementSelectConfig
        element.bind '$destroy', ->
          element.select2 'destroy'
          # Original setup function
          $timeout ->
            element.select2 options
            element.val controller.$viewValue
            controller.$render()
            if not options.initSelection and not isSelect
              data = element.select2 'data'
              controller.$setViewValue convertToAngularModel data
]
```

**Pull request merged**
