### PR TITLE
Ensures tElm and elm are jQuery objects before calling jQuery functions on them

### PR DESCRIPTION
**Pull request by coffbr01**
Some assumptions were made about tElm, specifically that it should have
functions is() and select2(). Those assumptions only hold true for
jQuery objects. So if tElm or elm are not jQuery objects, this commit
ensures that they are wrapped in $(/_element_/).

### CODE REVIEW

**Comment by ProLoser** [comment]
The entire module has a dependency on jQuery.

Also, all angular elements are already jquery elements.

**Comment by ProLoser** [comment]
If you're running into issues where the jquery methods are missing, it's because you're probably loading Angular _before_ jQuery, instead of after.

**Comment by coffbr01** [comment]
You're right; I was loading both Angular and jQuery assuming order did not matter. I added jQuery as an Angular dependency in my requireJS config and it works.

While I'm not sure how I feel about the new dependency order, I do appreciate the quick feedback. Thanks!

**Comment by ProLoser** [comment]
This is the preferred way of handling angular + jquery. What you had before was angular to load, see that jquery isn't present, and instead switch to it's internal 'jqlite'. With the new approach you will find that you don't have to do $(elm) anywhere in your app.

## 

Dean Sofer
DeanSofer.com
714.900.2254

**Comment by Vanuan** [comment]
It would be better to warn user at the ui-select2 loading time, that angularjs was loaded after jQuery. Is there a way to ensure this?

**Comment by ProLoser** [comment]
@vanuan why not ask for that in the AngularJS core? It doesn't make sense to bloat the code base with those sorts of checks

**Pull request closed without merging**
