### PR TITLE
chore(grunt): adds load-grunt-tasks module

### PR DESCRIPTION
**Pull request by 0x-r4bbit**
way easier to maintain grunt task loading

### CODE REVIEW

**Comment by ProLoser** [comment]
:+1:

**Comment by BaconSoap** [comment]
This is embarrassing, but it looks like I merged the commit incorrectly and it lost the association of it being a merge.

Here's what I did:

It wouldn't merge automatically, so I pulled the master of this repo, then:
1. `git checkout -b PascalPrecht-load-grunt-tasks master`
2. `git pull https://github.com/PascalPrecht/ui-select2.git load-grunt-tasks`
3. Merged the conflicts using the mergetool
4. `git checkout master`
5. `git merge PascalPrecht-load-grunt-tasks`
6. `git commit -m '[message]'`
7. `git push origin master`

It looks like it pushed up ok, but it still lost that association and I want to not do that in the future. When I check the network it confirms that it wasn't 'merged', but instead just a regular commit.

**Comment by 0x-r4bbit** [comment]
weird. Anyways. it's in now, right?

**Comment by BaconSoap** [comment]
It is in. I figured out where I messed up the merge so it shouldn't happen again. Thanks for the PR.

**Comment by 0x-r4bbit** [comment]
@BaconSoap my pleasure :)

**Pull request closed without merging**
