### PR TITLE
ui-select2 not working when combining multiple and ajax

### PR DESCRIPTION
**Pull request by vinh0604**
I use the following config which use both multiple and ajax:

```
$scope.opts = {
    ajax: {
        url: "/....",
        initSelection: function(el, fn) {},
        multiple: true,
        data: function (term, page) {
            return { q: term };
        },
        results: function (data, page) { 
            return {results: data};
        }
    }
} 
```

However, the component always render 'undefined' when an option is selected, and clicking remove on the 'undefined' seems to not do anything. After inspecting, it turned out that the $watch handler always be triggered before the handler of 'change' event of select2 element, and the current value at that time is a string value instead of an array causing the select2 data to be reseted.

I've made a minor update to fix this bug.

### CODE REVIEW

**Comment by jkennington** [comment]
This is also a problem when using the `'data'` and `'multiple'` options. Your fix works for that too if checking for `opts.ajax || opts.data`.

**Comment by mostly-novice** [comment]
+1

**Comment by danielpquinn** [comment]
+1

**Comment by dancrew32** [comment]
+1 Thanks for the fix!

**Comment by CharlesHamel** [comment]
+1

**Comment by harryjoy** [comment]
Thanks for the fix.
This solution works, but I'm using bower to get ui-select2 so I can not change files in ui-select2 code base. Is there any other alternative for this?

**Comment by vinh0604** [comment]
@harryjoy I think you should change to https://github.com/angular-ui/ui-select

This project is unmaintained now.

**Comment by harryjoy** [comment]
@vinh0604 thanks, I will try that one.

**Pull request closed without merging**
