### PR TITLE
ui-select2 does not split on select2's "separator" option for multiple tags

### PR DESCRIPTION
**Pull request by GFoley83**
Bug related to PR 6d63149b9c79452a67166ef3edad5383fb728326. Updated code to respect separator option instead of hard-coded comma. Splitting on a comma breaks if selected tag contains a comma e.g. selecting "Springsteen, Bruce" would cause two tags.

### CODE REVIEW

**Comment by qraynaud** [comment]
I included this & kept retro compatibility in PR #213. Maybe you could close this one and follow #213 ?

**Comment by themajix** [comment]
Hi Quentin,

I have entered #211 and #212. Which one you're referring to?

Thanks,
Majid

**Comment by GFoley83** [comment]
@qraynaud Reviewed #213 and looks good. Thanks :+1:

**Comment by qraynaud** [comment]
@themajix: sorry, my message was for @GFoley83

**Pull request closed without merging**
