### PR TITLE
Fix '$digest already in progress' bug

### PR DESCRIPTION
**Pull request by ghost**
`scope.$$phase` does not always seem to be enough to ensure that the $digest in progress error is not thrown. Per below references, add check on $rootScope.$$phase as well. No test, just a simple bug fix.

For reference:
- http://stackoverflow.com/a/14838239
- http://stackoverflow.com/questions/12729122/prevent-error-digest-already-in-progress-when-calling-scope-apply

### CODE REVIEW

**Comment by ProLoser** [comment]
You can get to `$rootScope` by doing `$scope.$root` you know?

I'm also curious why this check must be performed on the root though.

**Comment by ghost** [comment]
@ProLoser it is curious that the current scope doesn't know there's a digest happening. As for `$rootScope` vs `$scope.$root`, I followed the above references and [the angular docs](http://docs.angularjs.org/api/ng.$rootScope.Scope) which suggest accessing the root scope via `$rootScope`.

**Comment by ProLoser** [comment]
You are confusing the docs. You inject `$rootScope` if you do not have access to any other scope otherwise. It says it CAN be retrieved, not that you should or that it's the best solution.

I'm curious if someone from the @angular-ui/bootstrap has any knowledge about this behavior?

**Comment by ghost** [comment]
@ProLoser I have to respectfully disagree. `$scope.$root` is not mentioned in the docs. Injecting `$rootScope` is, as mentioned on the above page, the supported method of accessing the root scope. Not checking `$$phase` on the root scope results in an error, hence the fix.

**Comment by ProLoser** [comment]
The docs are (unsurprisingly) lacking.

**Comment by bdecarne** [comment]
oups i just made a request with $scope.$root #88, tested

**Pull request closed without merging**
